### PR TITLE
Added a new Column with fees

### PR DESCRIPTION
**Pull request by f2010126**
2 of the links do not have fees mentioned.
Screen Shot 2019-04-17 at 12 32 47 AM

### CODE REVIEW

**Review by tapaswenipathak — CHANGES_REQUESTED** [review]
Please put as no fees required.

**Comment by f2010126** [comment]
> Please put as no fees required.

Changed.

**Review by tapaswenipathak — CHANGES_REQUESTED** [review]
- Squash the commits.
- Fix the commit message, say `Added fees info per event`.
- Fix the description
- Add close https://github.com/tapaswenipathak/Photography-Competitions/issues/2 in the description.
- Put as no fee required in blank fee column.

Thanks!

**Comment by prateekj117** [comment]
@f2010126 Still on it?

**Comment by tapaswenipathak** [comment]
Closing as stale.

**Pull request closed without merging**
